global class GlobalStrings{
    Public final String AutoCompleteControllerWhereClause = ' like \'';
    Public final String ChecklistItem_TriggerHandler_sChecklistText= '...';
    Public final String SobjectApiName = 'Data_asset__c';
    Public final String commaSepratedFields = '';
    Public final String RecordType = 'Research Topic';
    Public final String StudySobjectApiName = 'Project__c';
    Public final String Studyactive = 'Active';
    Public final String StudyApproved ='Approved';
    Public final String StudyCompleted ='Completed';
    Public final String StudyClosed ='Closed';
    Public Final String reference = '/apex/Global_Search?searchWord=';
    Public final String referenceUrl = '/apex/Global_Search?searchWord=';   
    Public final String IsStartStudy = 'startStudy';
    Public final String IsResearch = 'BPType';
    Public final String searchWord = 'UTF-8';
    Public final String blobString = 'ISO-8859-1';
    Public final String comma = ',';
    public final String StudyCount = 'TC';
    Public Final String PartnerShipCount = 'RecordTotal';
    
    Public Static String returnString(String s){
        return s;
    }
    
     Public Static List<String> returnListString(List<String> s){
        return s;
    }
}