public class DRDW_Constants{


Public static Map<string,string> groupCapAreaMapping = new Map<string,string>
                                 {'DRDW_FG_Assay_Analytical_Development' =>'Analytical & Assay Development',
                                 'DRDW_FG_Bacteriology' => 'Bacteriology',
                                 'DRDW_FG_BioProducts' => 'BioProducts',
                                 'DRDW_FG_Chemistry' => 'Chemistry',
                                 'DRDW_FG_DDS' => 'DDS',
                                 'DRDW_FG_Informatics' => 'Informatics',
                                 'DRDW_FG_Parasitology' => 'Parasitology',
                                 'DRDW_FG_Target_Enablement' => 'Target Enablement',
                                 'DRDW_FG_Virology' => 'Virology'};
                                 
Public static Map<string,string> PublicGroupmapping = new Map<string,string>
                                 {'Analytical & Assay Development' => 'DRDW_FG_Assay_Analytical_Development',
                                 'Bacteriology' => 'DRDW_FG_Bacteriology',
                                 'BioProducts' => 'DRDW_FG_BioProducts',
                                 'Chemistry'=> 'DRDW_FG_Chemistry' ,
                                 'DDS' => 'DRDW_FG_DDS',
                                 'Informatics' => 'DRDW_FG_Informatics',
                                 'Parasitology' => 'DRDW_FG_Parasitology',
                                 'Target Enablement' => 'DRDW_FG_Target_Enablement',
                                 'Virology' => 'DRDW_FG_Virology'};    
                                 
Public Static Map<String,String> groupBUMapping = new Map<String,String>{
                                    'DRDW_BU_Business_Development' => 'Business Development',
                                    'DRDW_BU_CA_Parasitology' => 'Companion Animal - Parasitology',
                                    'DRDW_BU_CA_Therapeutics' => 'Companion Animal - Therapeutics',
                                    'DRDW_BU_CA_Vaccines' => 'Companion Animal - Vaccines',
                                    'DRDW_BU_External_Innovation' => 'External Innovation',
                                    'DRDW_BU_FA_Parasitology' => 'Food Animal - Parasitology',
                                    'DRDW_BU_FA_Therapeutics' => 'Food Animal - Therapeutics',
                                    'DRDW_BU_FA_Vaccines' =>'Food Animal - Vaccines',
                                    'DRDW_BU_Nutritionals' => 'Nutritionals'};       
                                    
Public Static Map<String,String> PublicgroupBUMapping = new Map<String,String>{
                                    'Business Development' => 'DRDW_BU_Business_Development',
                                    'Companion Animal - Parasitology' => 'DRDW_BU_CA_Parasitology',
                                    'Companion Animal - Therapeutics' => 'DRDW_BU_CA_Therapeutics',
                                    'Companion Animal - Vaccines' => 'DRDW_BU_CA_Vaccines',
                                    'External Innovation' => 'DRDW_BU_External_Innovation',
                                    'Food Animal - Parasitology' => 'DRDW_BU_FA_Parasitology',
                                    'Food Animal - Therapeutics' => 'DRDW_BU_FA_Therapeutics',
                                    'Food Animal - Vaccines' =>'DRDW_BU_FA_Vaccines',
                                    'Nutritionals' => 'DRDW_BU_Nutritionals'};                                                                                                      

}